apiVersion: v1
kind: Pod
metadata:
  name : hello-world-client
  namespace: default
  labels:
    app: app-client
spec:
  containers:
  - name: client
    image: client:latest
    imagePullPolicy: Never
